workflows:
  ios-release:
    name: iOS Release
    triggering:
      events:
        - push
    integrations:
      app_store_connect: Codemagic
    instance_type: mac_mini_m2
    environment:
      flutter: 3.41.8
      xcode: latest
      cocoapods: default
    scripts:
      - name: Disable Swift Package Manager
        script: |
          flutter config --no-enable-swift-package-manager
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Set up keychain and import certificate
        script: |
          keychain initialize
          keychain add-certificates --certificate certs/wobbly_credentials.p12 --certificate-password 1234
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.wobblybottle.game" --type IOS_APP_STORE
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
