apply plugin: "com.android.application"

android {
    namespace "com.wobblybottle.game"
    compileSdk 36

    defaultConfig {
        applicationId "com.wobblybottle.game"
        minSdk 24
        targetSdk 36
        versionCode 36
        versionName "10.2"
    }

    signingConfigs {
        release {
            storeFile file("C:/Users/PC/Desktop/wobbly-release-key.jks")
            storePassword "WobblyPass123!"
            keyAlias "wobblykey"
            keyPassword "WobblyPass123!"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
